In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'C:\Users\richi\OneDrive\Desktop\heart_disease_dataset.csv')
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75  Female          228             119          66  Current   
1     48    Male          204             165          62  Current   
2     53    Male          234              91          67    Never   
3     69  Female          192              90          72  Current   
4     62  Female          172             163          93    Never   
..   ...     ...          ...             ...         ...      ...   
995   56  Female          269             111          86    Never   
996   78  Female          334             145          76    Never   
997   79    Male          151             179          81    Never   
998   60  Female          326             151          68   Former   
999   53    Male          226             116          82  Current   

    Alcohol Intake  Exercise Hours Family History Diabetes Obesity  \
0            Heavy               1             No       No     Yes   
1              NaN               5             No       No      No   
2            Heavy               3            Yes       No     Yes   
3              NaN               4             No      Yes      No   
4              NaN               6             No      Yes      No   
..             ...             ...            ...      ...     ...   
995          Heavy               5             No      Yes     Yes   
996            NaN               6             No       No      No   
997       Moderate               4            Yes       No     Yes   
998            NaN               8            Yes      Yes      No   
999            NaN               6             No       No     Yes   

     Stress Level  Blood Sugar Exercise Induced Angina   Chest Pain Type  \
0               8          119                     Yes   Atypical Angina   
1               9           70                     Yes    Typical Angina   
2               5          196                     Yes   Atypical Angina   
3               7          107                     Yes  Non-anginal Pain   
4               2          183                     Yes      Asymptomatic   
..            ...          ...                     ...               ...   
995            10          120                      No  Non-anginal Pain   
996            10          196                     Yes    Typical Angina   
997             8          189                     Yes      Asymptomatic   
998             5          174                     Yes   Atypical Angina   
999             5          161                     Yes      Asymptomatic   

     Heart Disease  
0                1  
1                0  
2                1  
3                0  
4                0  
..             ...  
995              1  
996              1  
997              0  
998              1  
999              1  

[1000 rows x 16 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1000 non-null   int64 
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64 
 3   Blood Pressure           1000 non-null   int64 
 4   Heart Rate               1000 non-null   int64 
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64 
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64 
 12  Blood Sugar              1000 non-null   int64 
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   

In [4]:
df.describe()

Age  Cholesterol  Blood Pressure   Heart Rate  Exercise Hours  \
count  1000.000000  1000.000000       1000.0000  1000.000000     1000.000000   
mean     52.293000   249.939000        135.2810    79.204000        4.529000   
std      15.727126    57.914673         26.3883    11.486092        2.934241   
min      25.000000   150.000000         90.0000    60.000000        0.000000   
25%      39.000000   200.000000        112.7500    70.000000        2.000000   
50%      52.000000   248.000000        136.0000    79.000000        4.500000   
75%      66.000000   299.000000        159.0000    89.000000        7.000000   
max      79.000000   349.000000        179.0000    99.000000        9.000000   

       Stress Level  Blood Sugar  Heart Disease  
count   1000.000000  1000.000000    1000.000000  
mean       5.646000   134.941000       0.392000  
std        2.831024    36.699624       0.488441  
min        1.000000    70.000000       0.000000  
25%        3.000000   104.000000       0.000000  
50%        6.000000   135.000000       0.000000  
75%        8.000000   167.000000       1.000000  
max       10.000000   199.000000       1.000000

In [5]:
df.isnull().sum()

Age                          0
Gender                       0
Cholesterol                  0
Blood Pressure               0
Heart Rate                   0
Smoking                      0
Alcohol Intake             340
Exercise Hours               0
Family History               0
Diabetes                     0
Obesity                      0
Stress Level                 0
Blood Sugar                  0
Exercise Induced Angina      0
Chest Pain Type              0
Heart Disease                0
dtype: int64

In [6]:
df.corr(numeric_only=True)['Heart Disease']

Age               0.646871
Cholesterol       0.365041
Blood Pressure    0.006900
Heart Rate        0.013209
Exercise Hours   -0.014226
Stress Level      0.007071
Blood Sugar      -0.013004
Heart Disease     1.000000
Name: Heart Disease, dtype: float64

In [7]:
df['Alcohol Intake'].unique()

array(['Heavy', nan, 'Moderate'], dtype=object)

In [8]:
df['Alcohol Intake'] = df['Alcohol Intake'].fillna('No Intake')
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75  Female          228             119          66  Current   
1     48    Male          204             165          62  Current   
2     53    Male          234              91          67    Never   
3     69  Female          192              90          72  Current   
4     62  Female          172             163          93    Never   
..   ...     ...          ...             ...         ...      ...   
995   56  Female          269             111          86    Never   
996   78  Female          334             145          76    Never   
997   79    Male          151             179          81    Never   
998   60  Female          326             151          68   Former   
999   53    Male          226             116          82  Current   

    Alcohol Intake  Exercise Hours Family History Diabetes Obesity  \
0            Heavy               1             No       No     Yes   
1        No Intake               5             No       No      No   
2            Heavy               3            Yes       No     Yes   
3        No Intake               4             No      Yes      No   
4        No Intake               6             No      Yes      No   
..             ...             ...            ...      ...     ...   
995          Heavy               5             No      Yes     Yes   
996      No Intake               6             No       No      No   
997       Moderate               4            Yes       No     Yes   
998      No Intake               8            Yes      Yes      No   
999      No Intake               6             No       No     Yes   

     Stress Level  Blood Sugar Exercise Induced Angina   Chest Pain Type  \
0               8          119                     Yes   Atypical Angina   
1               9           70                     Yes    Typical Angina   
2               5          196                     Yes   Atypical Angina   
3               7          107                     Yes  Non-anginal Pain   
4               2          183                     Yes      Asymptomatic   
..            ...          ...                     ...               ...   
995            10          120                      No  Non-anginal Pain   
996            10          196                     Yes    Typical Angina   
997             8          189                     Yes      Asymptomatic   
998             5          174                     Yes   Atypical Angina   
999             5          161                     Yes      Asymptomatic   

     Heart Disease  
0                1  
1                0  
2                1  
3                0  
4                0  
..             ...  
995              1  
996              1  
997              0  
998              1  
999              1  

[1000 rows x 16 columns]

In [9]:
df.isnull().sum()

Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Smoking                    0
Alcohol Intake             0
Exercise Hours             0
Family History             0
Diabetes                   0
Obesity                    0
Stress Level               0
Blood Sugar                0
Exercise Induced Angina    0
Chest Pain Type            0
Heart Disease              0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

def encoded_cat_columns(df):
    le = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = le.fit_transform(df[col])
    return df

In [11]:
df = encoded_cat_columns(df)
df

Age  Gender  Cholesterol  Blood Pressure  Heart Rate  Smoking  \
0     75       0          228             119          66        0   
1     48       1          204             165          62        0   
2     53       1          234              91          67        2   
3     69       0          192              90          72        0   
4     62       0          172             163          93        2   
..   ...     ...          ...             ...         ...      ...   
995   56       0          269             111          86        2   
996   78       0          334             145          76        2   
997   79       1          151             179          81        2   
998   60       0          326             151          68        1   
999   53       1          226             116          82        0   

     Alcohol Intake  Exercise Hours  Family History  Diabetes  Obesity  \
0                 0               1               0         0        1   
1                 2               5               0         0        0   
2                 0               3               1         0        1   
3                 2               4               0         1        0   
4                 2               6               0         1        0   
..              ...             ...             ...       ...      ...   
995               0               5               0         1        1   
996               2               6               0         0        0   
997               1               4               1         0        1   
998               2               8               1         1        0   
999               2               6               0         0        1   

     Stress Level  Blood Sugar  Exercise Induced Angina  Chest Pain Type  \
0               8          119                        1                1   
1               9           70                        1                3   
2               5          196                        1                1   
3               7          107                        1                2   
4               2          183                        1                0   
..            ...          ...                      ...              ...   
995            10          120                        0                2   
996            10          196                        1                3   
997             8          189                        1                0   
998             5          174                        1                1   
999             5          161                        1                0   

     Heart Disease  
0                1  
1                0  
2                1  
3                0  
4                0  
..             ...  
995              1  
996              1  
997              0  
998              1  
999              1  

[1000 rows x 16 columns]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

In [13]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# logistic regression

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
LR = LogisticRegression()

In [18]:
LR.fit(X_train,y_train)

LogisticRegression()

In [19]:
y_pred1 = LR.predict(X_test)

In [20]:
print("Accuracy:\n", accuracy_score(y_test, y_pred1))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred1))
print("\n Classification report:\n", classification_report(y_test, y_pred1))

Accuracy:
 0.81

 Confusion Matrix:
 [[99 13]
 [25 63]]

 Classification report:
               precision    recall  f1-score   support

           0       0.80      0.88      0.84       112
           1       0.83      0.72      0.77        88

    accuracy                           0.81       200
   macro avg       0.81      0.80      0.80       200
weighted avg       0.81      0.81      0.81       200



# decession tree classifier

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
classifier = DecisionTreeClassifier()

In [23]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [24]:
y_pred2 = classifier.predict(X_test)

In [25]:
print("Accuracy:\n", accuracy_score(y_test, y_pred2))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred2))
print("\n Classification report:\n", classification_report(y_test, y_pred2))

Accuracy:
 0.97

 Confusion Matrix:
 [[112   0]
 [  6  82]]

 Classification report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       112
           1       1.00      0.93      0.96        88

    accuracy                           0.97       200
   macro avg       0.97      0.97      0.97       200
weighted avg       0.97      0.97      0.97       200



# ensemble

In [26]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier

In [27]:
rfc = RandomForestClassifier()
etc = ExtraTreesClassifier()
abc = AdaBoostClassifier()
gbc = GradientBoostingClassifier()

In [28]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [29]:
etc.fit(X_train,y_train)

ExtraTreesClassifier()

In [30]:
abc.fit(X_train,y_train)

AdaBoostClassifier()

In [31]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier()

In [32]:
y_pred3 = rfc.predict(X_test)

In [33]:
print("Accuracy:\n", accuracy_score(y_test, y_pred3))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred3))
print("\n Classification report:\n", classification_report(y_test, y_pred3))

Accuracy:
 0.965

 Confusion Matrix:
 [[112   0]
 [  7  81]]

 Classification report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97       112
           1       1.00      0.92      0.96        88

    accuracy                           0.96       200
   macro avg       0.97      0.96      0.96       200
weighted avg       0.97      0.96      0.96       200



In [34]:
y_pred4 = etc.predict(X_test)

In [35]:
print("Accuracy:\n", accuracy_score(y_test, y_pred4))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred4))
print("\n Classification report:\n", classification_report(y_test, y_pred4))

Accuracy:
 0.87

 Confusion Matrix:
 [[111   1]
 [ 25  63]]

 Classification report:
               precision    recall  f1-score   support

           0       0.82      0.99      0.90       112
           1       0.98      0.72      0.83        88

    accuracy                           0.87       200
   macro avg       0.90      0.85      0.86       200
weighted avg       0.89      0.87      0.87       200



In [36]:
y_pred5 = abc.predict(X_test)

In [37]:
print("Accuracy:\n", accuracy_score(y_test, y_pred5))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred5))
print("\n Classification report:\n", classification_report(y_test, y_pred5))

Accuracy:
 0.97

 Confusion Matrix:
 [[112   0]
 [  6  82]]

 Classification report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       112
           1       1.00      0.93      0.96        88

    accuracy                           0.97       200
   macro avg       0.97      0.97      0.97       200
weighted avg       0.97      0.97      0.97       200



In [38]:
y_pred6 = gbc.predict(X_test)

In [39]:
print("Accuracy:\n", accuracy_score(y_test, y_pred6))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred6))
print("\n Classification report:\n", classification_report(y_test, y_pred6))

Accuracy:
 0.97

 Confusion Matrix:
 [[112   0]
 [  6  82]]

 Classification report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       112
           1       1.00      0.93      0.96        88

    accuracy                           0.97       200
   macro avg       0.97      0.97      0.97       200
weighted avg       0.97      0.97      0.97       200



In [40]:
from xgboost import XGBClassifier

In [41]:
xgbc = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

In [42]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [43]:
y_pred7 = xgbc.predict(X_test)

In [44]:
print("Accuracy:\n", accuracy_score(y_test, y_pred7))
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred7))
print("\n Classification report:\n", classification_report(y_test, y_pred7))

Accuracy:
 0.95

 Confusion Matrix:
 [[112   0]
 [ 10  78]]

 Classification report:
               precision    recall  f1-score   support

           0       0.92      1.00      0.96       112
           1       1.00      0.89      0.94        88

    accuracy                           0.95       200
   macro avg       0.96      0.94      0.95       200
weighted avg       0.95      0.95      0.95       200

